### ISSUE TITLE
Criar o script de inserts da tabela "Aplicações de renda fixa"

### ISSUE THREAD

**Issue by f-mattioli** [f-mattioli/gerenciador-financas-pessoais#18]

**Comment by thiago-nog** [comment]
Em construção por Thiago

**Comment by thiago-nog** [comment]
INSERT INTO aplicações_renda_fixa( id, valor_aplicado, data_aplicação, valor_atual, usuario_id)
values ('01', '1000', '20230101', '250', '01');

**Comment by f-mattioli** [comment]
Favor submeter o código via Pull Request.
