### ISSUE TITLE
[PROG2] Criar model "Usuario"

### ISSUE THREAD

**Issue by f-mattioli** [f-mattioli/gerenciador-financas-pessoais#40]

**Comment by Pierre-Mendes** [comment]
**Issue #40** 
Em desenvolvimento por  **@Pierre-Mendes**

**Comment by Pierre-Mendes** [comment]
Desenvolvimento e implementação concluído! Pronto para code-review e merge.

**Link da PR:**
https://github.com/f-mattioli/gerenciador-financas-pessoais/pull/41

**Comment by IuriOliveira7** [comment]
Em revisão por @IuriOliveira7

**Comment by f-mattioli** [comment]
Concluído no PR #41.
