### ISSUE TITLE
[PROG2] Inserção de usuários

### ISSUE THREAD

**Issue by f-mattioli** [f-mattioli/gerenciador-financas-pessoais#45]

**Comment by Pierre-Mendes** [comment]
Em desenvolvimento por **@Pierre-Mendes**

**Comment by Pierre-Mendes** [comment]
Concluído Pronto para code Review e Merge.

**Link da PR** 
https://github.com/f-mattioli/gerenciador-financas-pessoais/pull/41

**Comment by f-mattioli** [comment]
Concluído no PR #41.
